my_blog/article/urls.py
from django.urls import path,include
from . import views
# 正在部署的应用的名称
app_name = "article"
urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

my_blog/comment/urls.py
from django.urls import path,include
from . import views
app_name = 'comment'
urlpatterns = [
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from article.views import article_list
from django.views.generic import TemplateView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', article_list, name='home'),
    path('accounts/', include('allauth.urls')),
    path('userinfo/', include('userinfo.urls', namespace='userinfo')),
    # path('accounts', include('userinfo.urls')),
    path('article/', include('article.urls', namespace='article')),
    # path('password-reset/', include('password_reset.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('account/weibo_login_success/', TemplateView.as_view(template_name='account/weibo_login_success.html')),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
from PIL import Image
#Processed Image Field:图像处理领域
from imagekit.models import ProcessedImageField
#ResizeToFit:调整以适应
from imagekit.processors import ResizeToFit
from ckeditor.fields import RichTextField

class ArticleColumn(models.Model):
    """
    栏目的 Model
    """
    title = models.CharField(max_length=100, blank=True)
    #创建事件
    created = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.title




class ArticlePost(models.Model):
    """
    文章作者。参数 on_delete 用于指定数据删除的方式，避免两个关联表的数据不一致。
    使用 ForeignKey定义一个关系。这将告诉 Django，每个（或多个） ArticlePost 对象
    都关联到一个 User 对象。Django本身具有一个简单完整的账号系统（User），足以满
    足一般网站的账号申请、建立、权限、群组等基本功能。
    用户=作者，两者关联起来，括号里面表示是“一”

    """
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # 文章标题。models.CharField 为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField(max_length=100)
    # 文章正文。保存大量文本使用 TextField
    body = RichTextField()
    # 文章创建时间。参数 default=timezone.now 指定其在创建数据时将默认写入当前的时间
    created = models.DateTimeField(default=timezone.now)
    # 文章更新时间。参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)
    #浏览量：存储正整数的字段
    total_views = models.PositiveIntegerField(default=0)
    #文章标签
    tags = TaggableManager(blank=True)
    # 文章标题图,标题图会上传到media/article/20190226这个目录中
    avatar = models.ImageField(upload_to='article/%Y%m%d/', blank=True)
    # 保存时处理图片,处理图片的代码
    def save(self, *args, **kwargs):
        #调用父函数的子函数（save函数）的功能
        article = super(ArticlePost, self).save(*args, **kwargs)
        #固定宽度缩放图片大小.把self.avatar筛掉没有标题图的文章,忽略浏览量保存的操作，免得每次用户进入文章详情页面都要处理标题图
        if self.avatar and not kwargs.get('update_fields'):
            image = Image.open(self.avatar)
            (x, y) = image.size
            new_x = 400
            new_y = int(new_x * (y / x))
            #Image.ANTIALIAS表示缩放采用平滑滤波
            resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)
            resized_image.save(self.avatar.path)
        return article

    # 图像处理的轮子
    # avatar = ProcessedImageField(
    #     upload_to='article/%Y%m%d',
    #     processors=[ResizeToFit(width=400)],
    #     format='JPEG',
    #     options={'quality': 100},
    # )



    # 内部类 class Meta 用于给 model 定义元数据(外加功能)
    class Meta:
        """ordering 指定模型返回的数据的排列顺序
            保证了最新的文章总是在网页的最上方
        """
        # '-created' 表明数据应该以倒序排列
        ordering = ('-created',)
    def __str__(self):
        # return self.title 将文章标题返回
        return self.title
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )


# Create your models here.

my_blog/article/forms.py
from .models import ArticlePost
from django import forms
# 写文章的表单类
class ArticlePostForm(forms.ModelForm):
#内部类，指定字段
    class Meta:
        model = ArticlePost
        fields = ('title', 'body', 'tags', 'avatar')

#表单：访客操作和输入的空间（页面）
# 在ArticlePost模型中，created和updated字段为自动生成，不需要填入；
# author字段暂时固定为id=1的管理员用户，也不用填入；
# 剩下的title和body就是表单需要填入的内容了。

my_blog/article/views.py
from comment.models import Comment
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import ArticlePost
import markdown
from .forms import ArticlePostForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from .models import ArticleColumn
from comment.forms import CommentForm
from django.contrib.auth.backends import ModelBackend
from allauth.account.auth_backends import AuthenticationBackend


def article_list(request):
    #从 url 中提取查询参数
    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    tag = request.GET.get('tag')
    #初始化查询集
    article_list = ArticlePost.objects.all()
    #搜索查询集
    if search:
        article_list = article_list.filter(
            #匹配title和body有输入的选项，search是内容
            Q(title__icontains=search) |
            Q(body__icontains=search)
        )
    else:
        search = ''
    #栏目查询集
    if column is not None and column.isdigit():
        article_list = article_list.filter(column=column)
    #标签查询集
    #在tags字段中过滤name为tag的数据条目
    if tag and tag != 'None':
        article_list = article_list.filter(tags__name__in=[tag])
    #查询集排序
    if order == 'total_views':
        article_list = article_list.order_by('-total_views')
    paginator = Paginator(article_list, 3)
    # 需要传递给模板（templates）的对象
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    context = { 'articles': articles,
                'order': order,
                'search':search,
                'column':column,
                'tag':tag,
     }
    return render(request, 'article/list.html', context)

# 文章详情

def article_detail(request, id):
    # 取出相应的文章
    article = ArticlePost.objects.get(id=id)
    #取出文章评论
    comments = Comment.objects.filter(article=id)
    #引入评论表单
    comment_form = CommentForm()
    #浏览量加1
    article.total_views += 1
    article.save(update_fields=['total_views'])
    # # 需要传递给模板的对象
    '''

    第一个参数是需要渲染的文章正文article.body
    第二个参数载入了常用的语法扩展，markdown.extensions.extra中包括了缩写、表格等扩展，
    markdown.extensions.codehilite则是后面要使用的代码高亮扩展。
    '''
    # article.body = markdown.markdown(article.body,
    #     extensions=[
    #     # 包含 缩写、表格等常用扩展
    #     'markdown.extensions.extra',
    #     # 语法高亮扩展
    #     'markdown.extensions.codehilite',
    #     #目录扩展
    #     'markdown.extensions.toc',
    #     ])
    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ]
    )
    '''
    先将Markdown类赋值给一个临时变量md，然后用convert()
    方法将正文渲染为html页面。通过md.toc将目录传递给模板。
    '''

    article.body = md.convert(article.body)
    # 传到前端

    context = { 'article': article,
                'toc': md.toc,
                'comments': comments,
                'comment_form': comment_form,
                }
    # 载入模板，并返回context对象
    return render(request, 'article/detail.html', context)

@login_required(login_url='/userinfo/login/')
def article_create(request):
    if request.method == "POST":
#POST的表单中包含了图片文件，所以要将request.FILES也一并绑定到表单类中，否则图片无法正确保存
        article_post_form = ArticlePostForm(request.POST, request.FILES)
        if article_post_form.is_valid():
            new_article = article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=request.user.id)

            if request.POST['column'] != 'none':
                #根据表单提交的value值，关联对应的栏目
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            new_article.save()
            # 新增代码，保存 tags 的多对多关系
            article_post_form.save_m2m()
            return redirect("article:article_list")
        else:
            return HttpResponse("文章为空！")
    else:
        #增加栏目的上下文，以便模板使用
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        context = { 'article_post_form': article_post_form, 'columns': columns }
        return render(request, 'article/create.html', context)


"""
当视图函数接收到一个客户端的request请求时，首先根据request.method判断用户是要提交数据（POST）、还是要获取数据（GET）：

如果用户是提交数据，将POST给服务器的表单数据赋于article_post_form实例。

然后使用Django内置的方法.is_valid()判断提交的数据是否满足模型的要求。

如果满足要求，保存表单中的数据（但是commit=False暂时不提交到数据库，因为author还未指定），并指定author为id=1的管理员用户。
然后提交到数据库，并通过redirect返回文章列表。redirect可通过url地址的名字，反向解析到对应的url。

如果不满足要求，则返回一个字符串"表单内容有误，请重新填写。"，告诉用户出现了什么问题。

如果用户是获取数据，则返回一个空的表单类对象，提供给用户填写。

"""
@login_required(login_url='/userinfo/login/')
def article_delete(request,id):
    article = ArticlePost.objects.get(id=id)
    if request.user != article.author:
        return HttpResponse("抱歉，你无权修改这篇文章。")
    else:
        article.delete()
        return redirect("article:article_list")

def article_safe_delete(request,id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("仅允许POST请求")
#过滤未登录用户
@login_required(login_url='/userinfo/login/')
def article_update(request, id):
# 旧的整个对象的数据
    article = ArticlePost.objects.get(id=id)
#过滤非作者用户
    if request.user != article.author:
        return  HttpResponse("抱歉，你无权修改这篇文章。")
# 判断用户是否为 POST 提交表单数据
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            article.title = request.POST['title']
            article.body = request.POST['body']
            #如果提交的POST的column数据不为空：
            if request.POST['column'] != 'none':
                ArticleColumn.objects.get(id=request.POST['column'])
            else:
                article.column =None
            if request.FILES.get('avatar'):
                article.avatar = request.FILES.get('avatar')
            article.tags.set(*request.POST.get('tags').split(','), clear=True)
            article.save()
            return redirect("article:article_detail", id=id)
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    else:
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        context = {
            'article': article,
            'article_post_form': article_post_form,
            'columns': columns,
            'tags': ','.join([x for x in article.tags.names()]),
            }
        return render(request, 'article/update.html', context)

my_blog/templates/article/create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action="." enctype="multipart/form-data">
                <div class="form-group">
                    <label for="avatar">标题图</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">

                </div>
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
{#                文章标签#}
                <div class="form-group">
                    <label for="tags">标签</label>
                    <input type="text"
                           class="form-control col-3"
                           id="tags"
                           name="tags"
                    >

                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
{#                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>#}
                    <div>
                        {{ article_post_form.media }}
                        {{ article_post_form.body }}
                    </div>
                </div>
{#                文章栏目#}
                <div class="form-group">
                    <label for="column">栏目</label>
                    <!-- 标签区域 -->
                    <select class="form-control"
                            id="column"
                            name="column"
                     >
                            <option value="none">选择栏目...</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}">{{ column }}</option>
                        {% endfor %}
                    </select>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-info">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}



{#<form>..</form>标签中的内容就是需要提交的表单。method="post"指定了表单提交的方式为POST（与视图函数中的request.method相联系）；action="."指定了表单提交的地址为默认的当前url。#}
{#关于{% csrf_token %}，它是Django中一个与网络安全相关的中间件验证。目前我们暂时不去深究它的实现，只需要知道表单中必须包含它就可以了，否则将会得到一个403错误。#}
{#<input>和<textarea>标签中的name=''属性指定了当前文本框提交的数据的名称，它必须与表单类中的字段名称对应，否则服务器无法将字段和数据正确的对应起来。#}

my_blog/templates/article/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'prism/prism.css' %}">
<!-- 文章详情 -->
<div class="container">
    <div class="row">
{#    将目录模块装进col-9容器里#}
        <div class="col-9">
        <!-- 标题及作者 -->
            <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
            <div class="col-12 alert alert-success">
                <div>
                    作者：{{ article.author }}
                    {% if user == article.author %}
                        <a href="#" onclick="confirm_safe_delete()">删除文章</a>
                        <a href="{% url 'article:article_update' article.id %}">编辑博客</a>
                    {% endif %}
                </div>
                <div>
                    浏览：{{ article.total_views }}
                </div>
            </div>



         <!-- 新增一个隐藏的表单 -->
            <form
                  style="display:none;"
                  id="safe_delete"
                  action="{% url 'article:article_safe_delete' article.id %}"
                  method="POST"
                >
                {% csrf_token %}

                    <button type="submit">发送</button>
             </form>

            <!-- 文章正文 -->
            <div class="col-12">
                <p>
                    {{article.body|safe}}
                </p>
            </div>
            {# 发表评论#}
            <hr>
            {% if user.is_authenticated %}
                <div>
                    <form
                            action="{% url 'comment:post_comment' article.id %}"
                            method="POST"
                    >
                            <!-- Django中需要POST数据的地方都必须有csrf_token -->
                    {% csrf_token %}
                            <!-- 评论正文 -->
                            <div class="form-group">
                                <label for="body">
                                    <strong>
                                        我也要评论：
                                    </strong>
                                </label>
                                <!-- 文本区域 -->
    {#                            <textarea#}
    {#                                    type="text"#}
    {#                                    class="form-control"#}
    {#                                    id="body"#}
    {#                                    name="body"#}
    {#                                    rows="2"></textarea>#}
                                <div>
                                    {{ comment_form.media }}
                                    {{ comment_form.body }}
                                </div>
                            </div>
                            <!-- 提交按钮 -->
                            <button type="submit" class="btn btn primary">评论</button>
                        </form>
                </div>
                <br>
            {% else %}
                <br>
                <h5 class="row justify-content-center">
                    请<a href="{% url 'userinfo:login' %}">登录</a>后回复
                </h5>
                <br>
            {% endif %}

            <h4>共有{{ comments.count }}条评论</h4>
            <div class="row">
                {% for comment in comments %}
                    <hr>
                    <p>
                        <strong style="color: pink">
                            {{ comment.user }}
                        </strong>在
                        <span style="color: green">
                            {{ comment.created|date:"Y-m-d H:i:s" }}
                        </span>发表评论：
                    </p>
                    <pre style=="font-family:inherit;font-size:1em;">
    {#                comment来自for循环#}
                    <div>{{ comment.body|safe }}</div>
                    </pre>
                {% endfor %}

            </div>
        </div>
        {#新增目录，将右侧的col-3留给目录；toc需要|safe标签才能正确渲染#}
        <div class="col-3 mt-4" id="sidebar" class="sidebar">
            <div class="sidebar__inner">
                <h4><strong>目录</strong></h4>
                <hr>
                <div>
                    {{ toc|safe }}
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .sidebar{
        will-change: min-height;
    }

    .sidebar__inner{
        transform: translate(0, 0); /* For browsers don't support translate3d. */
        transform: translate3d(0, 0, 0);
        will-change: position, transform;
    }
</style>
<script>
    // 删除文章的函数
    function confirm_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "确认删除",
            // 正文
            content: "确认删除这篇文章吗？",
            // 点击确定按钮后调用的回调函数
            yes: function(index, layero) {
                // 指定应当前往的 url
                location.href='{% url "article:article_delete" article.id %}'
            },
        })
    }
    function confirm_safe_delete() {
        layer.open({
            title: "确认删除",
            content: "确认删除这篇博客吗？",
            yes: function(index, layero) {
                $('form#safe_delete button').click();
                layer.close(index);
            }
        })
    }
</script>
{% endblock content %}
{#由于插件需求Jquery，一定要把 JavaScript 语句放到{% block script %}中，否则会报错。#}
{% block script %}
<!-- 引入粘性侧边栏 -->
<script src="{% static 'sticky_sidebar/jquery.sticky-sidebar.min.js' %}"></script>
<script type="text/javascript">
    $('#sidebar').stickySidebar({
        topSpacing: 20,
        bottomSpacing: 20,
    });
</script>

{% endblock script %}

my_blog/templates/article/list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <nav aria-label="breadcrumb" >
        <ol class="breadcrumb " style="background:rgba(0, 0, 0, 0); padding: 0 0 0 2px; font-size: 0.9em">
            <li class="breadcrumb-item ">
                {% if order != 'total_views' %}
                    <span style="color: white">最近</span>
                 {% else %}
                     <a href="{% url 'article:article_list' %}?search={{ search }}&column={{ column }}&tag={{ tag }}">
                    最近
                </a>
                {% endif %}
            </li>
            <li class="breadcrumb-item" ;>
                {% if order == 'total_views' %}
                    <span style="color: white;">热门</span>
                {% else %}
                    <a href="{% url 'article:article_list' %}?order=total_views&search={{ search }}&column={{ column }}&tag={{ tag }}">
                    热门
                    </a>
                {% endif %}

            </li>
        </ol>
    </nav>
   <!-- 新增，搜索栏 -->
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline" >
                <label class="sr-only">content</label>
                <input type="text"
                    class="form-control mb-2 mr-sm-2"
                    name="search"
                    placeholder="搜索文章..."
                    required
                >
            </form>
        </div>
    </div>
    {% if search %}
        {% if articles %}
            <h4><span style="color: #17A2B8">"{{ search }}"</span>的搜索结果如下：</h4>
            <hr>
        {% else %}
            <h4>暂无<span style="color: #17A2B8">"{{ search }}"</span>有关的文章。</h4>
            <hr>
        {% endif %}
    {% endif %}

    {#    列表循环#}
    <div class="row mt-2">
        {% for article in articles %}
            {# 标题图   #}
            {% if article.avatar %}
                <div class="col-3">
                    <img src="{{ article.avatar.url }}"
                         alt="avatar"
                         style="max-width:100%; border-radius:20px"
                    >
                </div>
            {% endif %}
        <!-- 文章内容 -->
        <div class="col">
            {#  栏目    #}
            {% if article.column %}
                <button type="button"
                        class="btn btn-sm mb-2
                            {% if article.column.title == 'Django' %}
                                btn-success
                            {% elif article.column.title == '记录生活' %}
                                btn-danger
                            {% elif article.column.title == '学习笔记' %}
                                btn-warning
                            {% endif %}
                                btn-primary
                        "
                >
                    {{ article.column }}
                </button>
            {% endif %}
            {#标签#}
            <span>
                {% for tag in article.tags.all %}
{#                    有tag参数返回到View中#}
                    <a href="{% url 'article:article_list' %}?tag={{ tag }}"
{#                       Bootstrap定义的徽章样式#}
                        class="badge badge-secondary"
                    >
                        {{ tag }}
                    </a>
                {% endfor %}
            </span>
            <!-- 标题 -->
            <h5>
{#                <b>#}
                    <a href="{% url 'article:article_detail' article.id %}"
                        style="color: black;"
                    >
                        {{ article.title }}

                    </a>
{#                </b>#}
            </h5>
            <!-- 摘要 -->
            <div>
                <p style="color: gray;">
                    {{ article.body|slice:'100' }}...
                </p>
            </div>
             <!-- 注脚 -->
            <p>
                <span>
                    <i class="fas fa-eye" style="color: lightblue;"></i>
                    {{ article.total_views }}&nbsp;&nbsp;&nbsp;
                </span>
                <span style="color: blue;">
                    <i class="fas fa-comments" style="color: yellowgreen;"></i>
                    {{ article.comments.count }}&nbsp;&nbsp;&nbsp;
                </span>
                <span>
                    <i class="fas fa-clock" style="color: pink;"></i>
                    {{ article.created|date:'Y-m-d' }}
                </span>
            </p>
{#            <hr>#}
        </div>
            <hr style="width: 100%;"/>
        {% endfor %}
    </div>
    <!-- 页码导航 -->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻按钮 -->
                    {% if articles.has_previous %}
                        <a href="?page=1&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}" class="btn btn-success">
                            &laquo; 1
                        </a>
                        <span>...</span>
                        <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
                           class="btn btn-secondary"
                        >
                            {{ articles.previous_page_number }}
                        </a>
                    {% endif %}

                    <!-- 当前页面 -->
                    <span class="current btn btn-danger btn-lg">
                        {{ articles.number }}
                    </span>
                <!-- 如果不是最末页，则显示下翻按钮 -->
                {% if articles.has_next %}
                        <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
                           class="btn btn-secondary"
                        >
                            {{ articles.next_page_number }}
                        </a>
                        <span>...</span>
                        <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
                           class="btn btn-success"
                        >
                            {{ articles.paginator.num_pages }} &raquo;
                        </a>
                    {% endif %}
            </span>
        </div>
    </div>
</div>
{% endblock content %}

my_blog/templates/article/update.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
{#            <br>#}
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="avatar">标题图</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>
                <!-- 文章标题 -->
                <div class="form-group">
                    <label for="title">博客标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
{#                文章标签#}
                <div class="form-group">
                    <label for="tags">标签</label>
                    <input type="text" class="form-control col-3" id="tags" name="tags"
                        value="{{ tags }}">
                </div>
                <div>
                    <label for="column">栏目</label>
                    <select class="form-control"
                            id="column"
                            name="column"
                    >
                            <option value="none">请选择栏目...</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}"
{#                                    判断了column.id与article.column.id是否相等，如果相等则将其设置为默认值。#}
                                    {% if column.id == article.column.id %}
                                        selected
                                    {% endif %}
                            >
                                {{ column }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <br>
                <div class="form-group">
                    <label for="body">博客正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}