my_blog/article/urls.py
from django.urls import path,include
from . import views
# 正在部署的应用的名称
app_name = "article"
urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from article.views import article_list
from django.views.generic import TemplateView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', article_list, name='home'),
    path('accounts/', include('allauth.urls')),
    path('userinfo/', include('userinfo.urls', namespace='userinfo')),
    # path('accounts', include('userinfo.urls')),
    path('article/', include('article.urls', namespace='article')),
    # path('password-reset/', include('password_reset.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('account/weibo_login_success/', TemplateView.as_view(template_name='account/weibo_login_success.html')),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/userinfo/urls.py
from django.urls import path
from . import views
app_name = 'userinfo'
urlpatterns = [
    path('detail/', views.UserInfoView.as_view(), name='detail'),
    path('crop-upload-image/', views.crop_upload_handler, name='crop_upload_image'),
    path('user-signup-validate', views.user_signup_validate, name='user_signup_validate'),
]
# app_name = 'userinfo'
# urlpatterns = [
#     path('login/', views.user_login, name='login'),
#     path('logout/', views.user_logout, name='logout'),
#     path('register/', views.user_register, name='register'),
#     path('delete/<int:id>/', views.user_delete, name='delete'),
#     path('edit/<int:id>/', views.profile_edit, name='edit'),
#
# ]

my_blog/templates/2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

my_blog/templates/back.html
<!DOCTYPE html>
<html>
<body>
<div id="Layer1" style="position:absolute; left:0px; top:0px; width:100%; height:100%">
<img src="back.jpg" width="100%" height="100%"/>
</div>
</body>
</html>

my_blog/templates/back_to_top_func.html
{#<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>#}
{#<script>#}
{#    // 向上滚动的函数#}
{#    $(function () {#}
{#        $('#BackTop').click(function () {#}
{#            $('html,body').animate({scrollTop: 0}, 500);#}
{#        });#}
{#        $(window).scroll(function () {#}
{#            if ($(this).scrollTop() > 300) {#}
{#                $('#BackTop').fadeIn(300);#}
{#            } else {#}
{#                $('#BackTop').stop().fadeOut(300);#}
{#            }#}
{#        }).scroll();#}
{#    });#}
{#</script>#}
{##}
{#<style>#}
{#    /* 按钮边框的大小、位置、样式 */#}
{#    .toTop-arrow {#}
{#        width: 3.5rem;#}
{#        height: 3.5rem;#}
{#        padding: 0;#}
{#        margin: 0;#}
{#        border: 0;#}
{#        border-radius: 33%;#}
{#        opacity: 0.7;#}
{#        background: black;#}
{#        cursor: pointer;#}
{#        position: fixed;#}
{#        right: 1.5rem;#}
{#        bottom: 1.5rem;#}
{#        display: none;#}
{#    }#}
{##}
{#    /* 绘制按钮中的向上箭头 */#}
{#    .toTop-arrow::before, .toTop-arrow::after {#}
{#        width: 31px;#}
{#        height: 7px;#}
{#        border-radius: 3px;#}
{#        background: orange;#}
{#        position: absolute;#}
{#        content: "";#}
{#    }#}
{##}
{#    .toTop-arrow::before {#}
{#        transform: rotate(-45deg) translate(0, -50%);#}
{#        left: 0.4rem;#}
{#    }#}
{##}
{#    .toTop-arrow::after {#}
{#        transform: rotate(45deg) translate(0, -50%);#}
{#        right: 0.4rem;#}
{#    }#}
{##}
{#    /* 取消点击按钮时的聚焦 */#}
{#    .toTop-arrow:focus {#}
{#        outline: none;#}
{#    }#}
{#</style>#}


<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: white;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

my_blog/templates/base.html
<!-- 载入静态文件 -->
{% load staticfiles %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bizhi/bizhi.css' %}">
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
          crossorigin="anonymous"
    >
</head>

<body style="background-image:
    url({% static 'bizhi/cloud.jpg' %});
        background-size: 100% 100%;
        background-attachment: fixed;
        ">
{#<body>#}
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置,表明这里应该加入list.html中的对应块的内容 -->
    <div id="wrapper">
        {% block content %}{% endblock content %}
        <div id="push"></div>
    </div>
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->

{#    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>#}
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/umd/popper.min.js" integrity="sha384-L2pyEeut/H3mtgCBaUNw7KWzp5n9+4pDQiExs933/5QfaTh8YStYFFkOzSoXjlTb" crossorigin="anonymous"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- 引入layer.js 依赖jquery -->
    <script src="{% static 'layer/layer.js' %}"></script>

{#    <video id="v1" autoplay loop >#}
{#        <source src="{% static 'vedio/yun.mp4' %}" type="video/mp4">#}
{#    </video>#}


{#    <body>#}
{#    <audio src="{% static 'music/星期五见面_(Friday)_(2014MAMA_In_HK)-IU-6175525.mp3' %}" autoplay="autoplay"></audio>#}
{#    </body>#}

    <!-- 引入bootstrap的js文件 -->
{#    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>#}
    {% block script %}
    <script>
    $(".django-ckeditor-widget").removeAttr('style');
    </script>
    {% endblock script %}
    {% include 'back_to_top_func.html' %}
{#    导航栏链接代码#}
    <style>
        html, body {
            height: 100%;
            margin: 0;
        }
        #wrapper {
            min-height: 100%;
            margin-bottom: -60px;
        }
        #footer {
            text-align:center;
        }
        #push {
            height: 60px;
        }
    </style>

</body>

</html>

my_blog/templates/footer.html
{% load staticfiles %}
<!-- Footer -->
{#<div>#}
{#    <br><br><br>#}
{#</div>#}
{#<footer class="py-3 bg-dark fixed-bottom">#}
{#<footer class="navbar-transparent navbar-fixed-top" role="navigation" id="footer">#}
{#navbar navbar-fixed-top navbar-transparent#}
{#<footer class="py-3 bg-dark">#}
{#    <div class="center-block" >#}
{##}
{#        <div class="container">#}
{#            <p class="m-0 text-center text-white " >www.xiaofengzi.com 2020</p>#}
{#        </div>#}
{#     </div>#}
{##}
{#</footer>#}

<div class="row col-12 justify-content-center">
    <div style="text-align: center; color: lightgrey;">
        <p class="mb-0">CopyRight &copy; 2019 ~ 2020 @cz小风子的个人网站</p>
        <p class="mb-0">Powered by
            <a href="https://www.djangoproject.com/" target="_blank">
                Django
            </a> &
            <a target="_blank" href="https://getbootstrap.com/">
                Bootstrap4
            </a>
            <span class="mb-0">&nbsp;粤ICP备20007442号-1</span>
        </p>
    </div>
</div>

my_blog/templates/header.html
<!-- 定义导航栏 -->
<nav class="navbar navbar-fixed-top navbar-transparent" role="navigation">
  <div class="container">

    <!-- 导航栏商标 -->
    <a class="navbar-brand" href="{% url 'article:article_list' %}" style="color: white">@cz小风子的个人网站</a>

    <!-- 导航入口 -->
    <div>
      <ul class="navbar-nav">
{#        <!-- 条目 -->#}
{#          <li class="nav-item">#}
{#          <a class="nav-link" href="{% url 'article:article_create' %}">新建博客</a>#}
{#        </li>#}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'article:article_list' %}" style="color: white">首页</a>
        </li>

        {% if user.is_authenticated %}
        <!-- 如果用户已经登录，则显示用户名下拉框 -->
        <li class="nav-item dropdown" >
            <a class="nav-link dropdown-toggle"  href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
                <font style="color: white">{{ user.username }}</font>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown" >
              <a class="dropdown-item" href="{% url "userinfo:detail" %}">个人信息</a>
              <a class="dropdown-item" href="{% url "article:article_create" %}">新建博客</a>
{#              <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>#}
{#              <a class="dropdown-item" href="{% url "userinfo:logout" %}">退出登录</a>#}
              <a href="javascript:" class="dropdown-item" data-toggle="modal" data-target="#logout">退出登录</a>



            </div>

        </li>
    <!-- 如果用户未登录，则显示 “登录” -->
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">登录</a>
            </li>
    <!-- if 语句在这里结束 -->
        {% endif %}

      </ul>
    </div>

  </div>
  <div class="modal fade" id="logout" tabindex="-1" role="dialog" aria-labelledby="logout" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <h5 class="modal-body">
                    确认退出吗？
                </h5>
                <div class="modal-footer">
                    <form method="post" action="{% url 'account_logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">退出登录</button>
                    </form>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">返回</button>
                </div>
            </div>
        </div>
    </div>

</nav>
{#</nav>#}
{#只有在用户登录时才对这段JavaScript代码进行解析#}
{#{% if user.is_authenticated %}#}
{#<form#}
{#    style="display:none;"#}
{#    id="user_delete"#}
{#    action="{% url 'userinfo:delete' user.id %}"#}
{#    method="POST"#}
{#>#}
{#{% csrf_token %}#}
{#    <button type="submit">发送</button>#}
{#</form>#}
{#    <script>#}
{#        function user_delete() {#}
{#            // 调用layer弹窗组件#}
{#            layer.open({#}
{#                title: "确认删除",#}
{#                content: "确认删除用户资料吗？",#}
{#                yes: function(index, layero) {#}
{#                    $('form#user_delete button').click();#}
{#                    layer.close(index);#}
{#                },#}
{#            })#}
{#        }#}
{#    </script>#}
{#{% endif %}#}